# Generated by Django 4.1.7 on 2023-02-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_order_item_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
