# Generated by Django 4.1.7 on 2023-02-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_item_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default='2023-02-17 14:29:18.682221'),
            preserve_default=False,
        ),
    ]
