# Generated by Django 4.1.7 on 2023-02-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
