# Generated by Django 4.1.7 on 2023-02-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ManyToManyField(to='main.coupon', verbose_name='Купон'),
        ),
    ]
